import { wrapFunctional } from './utils'

export { default as ColorModeSwitcher } from '../..\\components\\ColorModeSwitcher.vue'
export { default as LanguageSwitcher } from '../..\\components\\LanguageSwitcher.vue'
export { default as IndexNewsGrid } from '../..\\components\\index\\NewsGrid.vue'
export { default as IndexWorkingAreas } from '../..\\components\\index\\WorkingAreas.vue'
export { default as LayoutAlternateMenu } from '../..\\components\\layout\\AlternateMenu.vue'
export { default as LayoutFooter } from '../..\\components\\layout\\Footer.vue'
export { default as LayoutHeader } from '../..\\components\\layout\\Header.vue'
export { default as LayoutLobby } from '../..\\components\\layout\\Lobby.vue'
export { default as LayoutMobileMenu } from '../..\\components\\layout\\MobileMenu.vue'
export { default as LayoutScrollTopButton } from '../..\\components\\layout\\ScrollTopButton.vue'
export { default as LayoutTopmost } from '../..\\components\\layout\\Topmost.vue'
export { default as NewsCategoryPicker } from '../..\\components\\news\\CategoryPicker.vue'
export { default as NewsDetailMeta } from '../..\\components\\news\\DetailMeta.vue'
export { default as NewsDetailRelated } from '../..\\components\\news\\DetailRelated.vue'
export { default as IndexEventsChildrenSpring } from '../..\\components\\index\\events\\ChildrenSpring.vue'
export { default as IndexEventsLovelySpring } from '../..\\components\\index\\events\\LovelySpring.vue'
export { default as IndexEventsMidAutumn } from '../..\\components\\index\\events\\MidAutumn.vue'
export { default as IndexEventsNightPorridge } from '../..\\components\\index\\events\\NightPorridge.vue'
