import { wrapFunctional } from './utils'

export const ColorModeSwitcher = import('../..\\components\\ColorModeSwitcher.vue' /* webpackChunkName: "components/color-mode-switcher" */).then(c => wrapFunctional(c.default || c))
export const LanguageSwitcher = import('../..\\components\\LanguageSwitcher.vue' /* webpackChunkName: "components/language-switcher" */).then(c => wrapFunctional(c.default || c))
export const IndexNewsGrid = import('../..\\components\\index\\NewsGrid.vue' /* webpackChunkName: "components/index-news-grid" */).then(c => wrapFunctional(c.default || c))
export const IndexWorkingAreas = import('../..\\components\\index\\WorkingAreas.vue' /* webpackChunkName: "components/index-working-areas" */).then(c => wrapFunctional(c.default || c))
export const LayoutAlternateMenu = import('../..\\components\\layout\\AlternateMenu.vue' /* webpackChunkName: "components/layout-alternate-menu" */).then(c => wrapFunctional(c.default || c))
export const LayoutFooter = import('../..\\components\\layout\\Footer.vue' /* webpackChunkName: "components/layout-footer" */).then(c => wrapFunctional(c.default || c))
export const LayoutHeader = import('../..\\components\\layout\\Header.vue' /* webpackChunkName: "components/layout-header" */).then(c => wrapFunctional(c.default || c))
export const LayoutLobby = import('../..\\components\\layout\\Lobby.vue' /* webpackChunkName: "components/layout-lobby" */).then(c => wrapFunctional(c.default || c))
export const LayoutMobileMenu = import('../..\\components\\layout\\MobileMenu.vue' /* webpackChunkName: "components/layout-mobile-menu" */).then(c => wrapFunctional(c.default || c))
export const LayoutScrollTopButton = import('../..\\components\\layout\\ScrollTopButton.vue' /* webpackChunkName: "components/layout-scroll-top-button" */).then(c => wrapFunctional(c.default || c))
export const LayoutTopmost = import('../..\\components\\layout\\Topmost.vue' /* webpackChunkName: "components/layout-topmost" */).then(c => wrapFunctional(c.default || c))
export const NewsCategoryPicker = import('../..\\components\\news\\CategoryPicker.vue' /* webpackChunkName: "components/news-category-picker" */).then(c => wrapFunctional(c.default || c))
export const NewsDetailMeta = import('../..\\components\\news\\DetailMeta.vue' /* webpackChunkName: "components/news-detail-meta" */).then(c => wrapFunctional(c.default || c))
export const NewsDetailRelated = import('../..\\components\\news\\DetailRelated.vue' /* webpackChunkName: "components/news-detail-related" */).then(c => wrapFunctional(c.default || c))
export const IndexEventsChildrenSpring = import('../..\\components\\index\\events\\ChildrenSpring.vue' /* webpackChunkName: "components/index-events-children-spring" */).then(c => wrapFunctional(c.default || c))
export const IndexEventsLovelySpring = import('../..\\components\\index\\events\\LovelySpring.vue' /* webpackChunkName: "components/index-events-lovely-spring" */).then(c => wrapFunctional(c.default || c))
export const IndexEventsMidAutumn = import('../..\\components\\index\\events\\MidAutumn.vue' /* webpackChunkName: "components/index-events-mid-autumn" */).then(c => wrapFunctional(c.default || c))
export const IndexEventsNightPorridge = import('../..\\components\\index\\events\\NightPorridge.vue' /* webpackChunkName: "components/index-events-night-porridge" */).then(c => wrapFunctional(c.default || c))
